### ISSUE TITLE
Clicking on the date already selected for a Task or Event sets the date to the lowest possible

### ISSUE THREAD

**Issue by Konicai** [powerplanner/powerplannerapps#102]
1. Open the UI to create a new event or task, or modify an existing one
2. Open the date selection popup
3. Select the date with the blue outline (the presently selected date)
4. The date sets to January 1st 1922

Can't reproduce this with Holidays.

Installed PowerPlanner version: `2201.22.5.0`
Using Windows 10 `19042.1526`

**Comment by andrewleader** [comment]
Thanks for reporting this @Konicai, good find! I've fixed this and just submitted an update, version 2203.18.2 will have this fix and should be available within 24 hours!
