### ISSUE TITLE
Re-arrange display order for "Years"

### ISSUE THREAD

**Issue by LowRentTrent** [powerplanner/powerplannerapps#34]
Years appear in the order they are created rather than alphabetical sort or otherwise. Would be nice if they were sorted.

**Comment by andrewleader** [comment]
Hey @LowRentTrent I totally missed this! Years actually are sorted if you add start and end dates to the semesters: https://powerplanner.freshdesk.com/support/solutions/articles/43000061451-set-start-and-end-dates-for-a-semester

**Comment by LowRentTrent** [comment]
> Hey @LowRentTrent I totally missed this! Years actually are sorted if you add start and end dates to the semesters: https://powerplanner.freshdesk.com/support/solutions/articles/43000061451-set-start-and-end-dates-for-a-semester

Thankyou, works perfectly!
