### ISSUE TITLE
Issue with current semester in overall GPA calculation

### ISSUE THREAD

**Issue by LowRentTrent** [powerplanner/powerplannerapps#35]
Classes with no grades yet appear with the maximum possible result. This is fine, but it throws off the overall GPA. 

I'd prefer to have the "interim value" set to something like "null" for both aesthetic reasons and for GPA calculation until a grade is entered, but an easier fix might just be to have a setting to not include current semester in overall GPA calculation.

**Comment by andrewleader** [comment]
I missed this feedback when originally posted, sorry! That's a good point, I agree that the class should be ignored until it has a grade (and visually indicate that too).

This would be a good idea for someone to work on!

**Comment by andrewleader** [comment]
Fixed with commit 71ae60f

Update will be submitted tonight!

**Comment by LowRentTrent** [comment]
> Fixed with commit [71ae60f](https://github.com/powerplanner/powerplannerapps/commit/71ae60ff5709fce6ed42107cde45d0477056ddea)
> 
> Update will be submitted tonight!

Thankyou so much Andrew, this makes my day :)

**Comment by LowRentTrent** [comment]
Noticed that the issue is partly fixed but not completely, see attached screenshot: 
![Annotation 2020-08-05 094051](https://user-images.githubusercontent.com/39205345/89355866-c8144e80-d6ff-11ea-9f21-ce34568e92c0.png)

A semester with no grades seems to put in a "pass" GPA by default - my GPA scale is 1-7, 4 is pass, 7 is high distinction.  

This results in the overall GPA being reported lower than it should be.

**Comment by andrewleader** [comment]
@LowRentTrent that GPA actually isn't factored in (notice that your Year 4 GPA at the top right is still 5.33 (the same value as SEM1). So the overall GPA is still calculated correctly, the UI should be updated to not display the "4.0" though and just display "--"
