### ISSUE TITLE
Calendar won't show when making new tasks/events (sometimes)

### ISSUE THREAD

**Issue by gabepesco** [powerplanner/powerplannerapps#57]
When making tasks, if I first click on the calendar, sometimes it will not popup whatsoever. The only way to fix it is to close and make a new task and hope it works.

**Comment by andrewleader** [comment]
Hey @gabepesco, sorry for not seeing this issue! I didn't have my GitHub notifications configured.

Are you still having problems with this? If so, are you seeing this problem on Android or iOS or Windows? If you're still seeing this, please re-open the issue.
