### ISSUE TITLE
Dark Theme support for Android and iOS

### ISSUE THREAD

**Issue by pablojimpas** [powerplanner/powerplannerapps#6]
Now that both mobile platforms are embracing Dark Theme support it'd be fantastic to have that on PowerPlanner just like it is in Windows.

PS: I've been using this app for almost 4 years and I've just discovered that it is Open Source, if the project were more visible I'm sure that many excellent developers would contribute. I would be pleased to help when I've time.
Congrats for an amazing app.

**Asks**

- 11 from https://barebonesdev.visualstudio.com/Apps/_backlogs/backlog/Power%20Planner/Features/?workitem=37
- This post itself

**Comment by andrewleader** [comment]
Hey @pablojimpas, I just noticed you created this issue! Dark theme is a popular request, any contributions to add that would be greatly appreciated! If you've got time, send me an email (through Power Planner's About page in the Settings) and we can talk more! I've had less time to work on Power Planner lately, hence I open sourced it hoping to get some contributions!

**Comment by pablojimpas** [comment]
Hi! I've been busy for a while and I almost forgot this, sorry. But I've just updated the app on Android and I remembered the issue instantly with the glorious dark theme, nice.

I will let you know if I find any issues but for now everything looks good. I imagine iOS support isn't ready yet and that's why the issue is still open.

**Comment by andrewleader** [comment]
Hey @pablojimpas! Yep, iOS dark theme hasn't been implemented yet (and I haven't started working on it). Thanks in advance for any issues you find with the dark theme on Android!

**Comment by pablojimpas** [comment]
So far I've only noticed dark text on the left of grades weight
![image](https://user-images.githubusercontent.com/51208565/82307132-76391380-99af-11ea-8c3a-18f743ff441e.png)

**Comment by andrewleader** [comment]
Whoops!! Good catch, thanks :) Fixing!

**Comment by andrewleader** [comment]
FYI I fixed that invisible text on Android, you should have already received the app update!

**Comment by pablojimpas** [comment]
> FYI I fixed that invisible text on Android, you should have already received the app update!

I updated the app and works great, I don't see more glitches for now, thanks.
