### ISSUE TITLE
Time Zone Options do not reflect daylight savings properly

### ISSUE THREAD

**Issue by KillerToaster** [powerplanner/powerplannerapps#90]
I use this software to organize my university schedule. I go to school in Arizona where we are on Mountain Standard Time. Arizona does not participate in daylight savings. When daylight savings started, all the tasks and events switched their due dates when they should not have. The times are rolling forward an hour. For example if I input 11:59 PM it will change to 12:59 AM automatically. This is not a critical error, but extremely annoying to deal with because I almost missed some due dates.

**Comment by andrewleader** [comment]
Hey @KillerToaster, thanks for reporting this!

**Did you set your time zone in the Power Planner settings?** Or you never set the time zone? If you've never set that (and never used the Google Calendar integration), the time settings should never change.

If you've set the time zone, can you let me know what you set?

![image](https://user-images.githubusercontent.com/13246069/142936069-c6d07086-33ba-42f2-8628-77e9d0d8f057.png)

**Comment by KillerToaster** [comment]
My time zone is set for Mountain Standard Time.
<img width="415" alt="pwrplanner timezone" src="https://user-images.githubusercontent.com/76828390/143075323-25270b69-06ed-402e-85bd-4692cf9466db.PNG">

 If having no time zone set causes the time to never change it would be nice if there was an option for no time zone. Now that I've set it I can no longer unset it. I had this issue for a couple of weeks but now that I am trying to recreate it, it seems to be working fine? 

After some testing, I found that the due time for tasks would only switch if the time inputted was between 11:00 PM and 12 AM. If the time inputted was between these two times it would jump forward an hour. If the time was set to anything else like 10:00 PM it would stay 10:00 PM. I don't know why this was happening or why it resolved itself especially since it was an issue for so long and the solution was definitely not solved by restarting Power Planner or my computer.

**Comment by andrewleader** [comment]
Hmm @KillerToaster, I couldn't reproduce this by changing my system clock to mountain time and switching the clock back to Nov 6th and then forward to Nov 7th.

Do you still see that happen with tasks where if you input one at 11:30 PM it jumps forward an hour? Or that only happened when the time changed?

**Comment by KillerToaster** [comment]
The times seem to be working fine now and I cannot recreate the issue I was having before. The times are no longer jumping forward so the issue may have been on my end. If it happens again, I'll be sure to document it in further detail to ensure this.
