### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by woutvos** [powerplanner/powerplannerapps#95]
I get this error when trying to sync the microsoft store version.
`Backend error. SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.`
Can someone help me?

**Comment by andrewleader** [comment]
Hi @woutvos, sorry for the delayed response, I don't check GitHub issues often (I do check emails to my support email often though). Are you still seeing this error? I made some fixes around this a while ago. I'll close this issue for now, if you're still hitting it, please reopen and then also email me through the support email inside Power Planner and include your username.
